# Generated by Django 2.2.3 on 2019-08-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20190805_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
